export enum Action {
  DISPLAY_ALERT = "SHOW_ALERT",
  CLEAR_ALERT = "CLEAR_ALERT",
  // authenticate
  AUTHENTICATE_USER_BEGIN = "AUTHENTICATE_USER_BEGIN",
  AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS",
  AUTHENTICATE_USER_ERROR = "AUTHENTICATE_USER_ERROR",
}
